### ISSUE TITLE
Update windshaft to drop cartodb extension requirement on backend

### ISSUE THREAD

**Issue by strk** [akvo/akvo-maps#2]
See https://github.com/CartoDB/Windshaft/issues/503#issuecomment-263858766

**Comment by iperdomo** [comment]
@strk there are a couple of new versions of Windshaft, do you mind trying and check if this is resolved?

**Comment by strk** [comment]
Done with ff605ab. I still have to check what good it does us.
Note that I still had to reference our own fork to be able to support per-layer SRID in the MapConfig
(ref https://github.com/CartoDB/Windshaft/issues/528#issuecomment-277050281)

I'm not going to check if we can drop one of those CDB_ function from the PostGIS container

**Comment by strk** [comment]
I'm still seing this in the postgis logs:
```
2017-02-28 10:22:13 UTC [241-1] akvo@akvo ERROR:  stats for "liberia.geom" do not exist
2017-02-28 10:22:13 UTC [241-2] akvo@akvo STATEMENT:  SELECT row_to_json(s) as result FROM(select _postgis_stats('public.liberia'::regclass, 'geom') as stats) as s
```

**Comment by strk** [comment]
Ok moved the liberia.geom stats missing issue to  #5, this one let's keep for CartoDB extension requirement

**Comment by strk** [comment]
So the update was done, but the dependency is still there: https://github.com/CartoDB/Windshaft/issues/503#issuecomment-283005153
