### ISSUE TITLE
Move from StatsD to native Prometheus metrics

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-maps#54]
The example documentation on how to use Windshaft uses StatsD for capturing metrics. We have used the [StatsD -> Prometheus](https://github.com/prometheus/statsd_exporter) exporter so far, but we have found that the configuration is wrong, e.g. We would like to have a metric with labels, so we can filter/aggregate. In its current form the tenant is part of the metric.

> We recommend this only as an intermediate solution and recommend switching to native 
> Prometheus instrumentation in the long term.

We can use the [`prom-client`](https://github.com/siimon/prom-client) directly instead of StatsD in the middle.

**Comment by dlebrero** [comment]
FYI, I kind of remember that Maps is using some JS library that only worked with StatsD.

**Comment by iperdomo** [comment]
@dlebrero i think we're interested in the HTTP codes and time, right? ... it seems that is possible to do it with that `prom-client` library and the `express` http library we're using for handling requests

**Comment by dlebrero** [comment]
There was something regarding GCs and such that looked also interesting

**Comment by iperdomo** [comment]
There is a new version of Windshaft 7.0.0 with support of node.js 12 - https://github.com/akvo/Windshaft/releases/tag/7.0.0

Node.js v10 is now in maintenance mode with EOL on 2021-04-30

![nodejs-schedule](https://user-images.githubusercontent.com/178474/83376209-c1045380-a3d1-11ea-9b78-d699eea618b8.png)
